server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#logging:
    #level:
    #org.springframework.security: DEBUG
      #org.springframework.web: DEBUG

#application:
    #security:
      #jwt:
      #secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      #expiration: 86400000 # a day
      #refresh-token:
    #expiration: 604800000 # 7 days







# Spring DataSource Configuration
  #spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_security
  #spring.datasource.username=postgres
  #spring.datasource.password=postgres
  #spring.datasource.driver-class-name=org.postgresql.Driver

  # JPA/Hibernate Configuration
  #spring.jpa.hibernate.ddl-auto=create-drop
  #spring.jpa.show-sql=false
  #spring.jpa.properties.hibernate.format_sql=true
  #spring.jpa.database=postgresql
  #spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

  # Application Security Configuration
  #application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  #application.security.jwt.expiration=86400000
  #application.security.jwt.refresh-token.expiration=604800000